<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/animations.css">  
    <link rel="stylesheet" href="../css/main.css">  
    <link rel="stylesheet" href="../css/admin.css">
        
    <title>My Reports</title>
    <style>
        .popup{
            animation: transitionIn-Y-bottom 0.5s;
        }
        .sub-table{
            animation: transitionIn-Y-bottom 0.5s;
        }
        .abc.scroll {
            max-height: 400px;
            overflow-y: auto;
            overflow-x: hidden;
            scrollbar-width: thin;
            scrollbar-color: #2196F3 #f1f1f1;
        }
        .abc.scroll::-webkit-scrollbar {
            width: 8px;
        }
        .abc.scroll::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 4px;
        }
        .abc.scroll::-webkit-scrollbar-thumb {
            background: #2196F3;
            border-radius: 4px;
        }
        .abc.scroll::-webkit-scrollbar-thumb:hover {
            background: #1976D2;
        }
        thead.sticky-header {
            position: sticky;
            top: 0;
            background: white;
            z-index: 10;
        }
        
        /* Enhanced modal styles for document viewing */
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.7);
            z-index: 1000;
            display: flex;
            justify-content: center;
            align-items: flex-start;
            padding: 20px;
        }
        
        .popup {
            background: white;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.3);
            position: relative;
            max-width: 90vw;
            max-height: 90vh;
            width: auto;
            height: auto;
            overflow: auto;
            margin: 5vh auto;
        }
        
        .close {
            position: absolute;
            top: 15px;
            right: 20px;
            font-size: 30px;
            text-decoration: none;
            color: #333;
            z-index: 1001;
        }
        
        .content {
            padding: 20px;
        }
        
        .document-content {
            text-align: left;
            white-space: pre-wrap;
            line-height: 1.6;
            font-size: 16px;
            max-height: 60vh;
            overflow-y: auto;
            padding: 10px;
            border: 1px solid #eee;
            border-radius: 5px;
            background-color: #fafafa;
        }
    </style>
</head>
<body>
<?php

session_start();

if (isset($_GET['action']) && $_GET['action'] == 'download_doc' && isset($_GET['id'])) {
    if(isset($_SESSION["user"])){
        if(($_SESSION["user"])=="" or $_SESSION['usertype']!='p'){
            header("location: ../login.php");
            exit();
        }else{
            $useremail=$_SESSION["user"];
        }
    }else{
        header("location: ../login.php");
        exit();
    }
    
    include("../connection.php");
    
    $sqlmain= "select * from patient where pemail=?";
    $stmt = $database->prepare($sqlmain);
    $stmt->bind_param("s",$useremail);
    $stmt->execute();
    $userrow = $stmt->get_result();
    $userfetch=$userrow->fetch_assoc();
    $pid= $userfetch["pid"];
    
    $doc_id = $_GET['id'];
    
    $sql = "SELECT md.*, d.docname FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.document_id = ? AND md.patient_id = ?";
    $stmt = $database->prepare($sql);
    $stmt->bind_param("ii", $doc_id, $pid);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result->num_rows > 0) {
        $document = $result->fetch_assoc();
        
        $filename = str_replace(' ', '_', $document['document_title']).'_'.date('Y-m-d', strtotime($document['created_date'])).'.txt';
        
        header('Content-Type: text/plain');
        header('Content-Disposition: attachment; filename="'.$filename.'"');
        
        echo "=== ".htmlspecialchars($document['document_title'])." ===\n";
        echo "Document Type: ".ucfirst(str_replace('_', ' ', $document['document_type']))."\n";
        echo "Generated by: Dr. ".htmlspecialchars($document['docname'])."\n";
        echo "Date: ".date('F j, Y', strtotime($document['created_date']))."\n\n";
        echo $document['document_content'];
        
        exit();
    } else {
        header("location: reports.php");
        exit();
    }
}

if (isset($_GET['action']) && $_GET['action'] == 'view_doc' && isset($_GET['id'])) {
    $view_doc_id = $_GET['id'];
}

if(isset($_SESSION["user"])){
    if(($_SESSION["user"])=="" or $_SESSION['usertype']!='p'){
        header("location: ../login.php");
    }else{
        $useremail=$_SESSION["user"];
    }

}else{
    header("location: ../login.php");
}

include("../connection.php");

$sqlmain= "select * from patient where pemail=?";
$stmt = $database->prepare($sqlmain);
$stmt->bind_param("s",$useremail);
$stmt->execute();
$userrow = $stmt->get_result();
$userfetch=$userrow->fetch_assoc();
$pid= $userfetch["pid"];
$pname=$userfetch["pname"];

$database->query("ALTER TABLE session_notifications ADD COLUMN IF NOT EXISTS patid INT DEFAULT NULL");
$unreadNotificationsQuery = $database->query("SELECT COUNT(*) AS unread_count FROM session_notifications WHERE patid = $pid AND status = 'pending'");
$unreadNotificationsCount = 0;
if ($unreadNotificationsQuery && $unreadNotificationsQuery->num_rows > 0) {
    $unreadNotificationRow = $unreadNotificationsQuery->fetch_assoc();
    $unreadNotificationsCount = (int)$unreadNotificationRow['unread_count'];
}

?>
<div class="container<?php if (isset($view_doc_id)) echo ' popup-active'; ?>">
    <div class="menu">
        <table class="menu-container" border="0">
            <tr>
                <td style="padding:10px" colspan="2">
                    <table border="0" class="profile-container">
                        <tr>
                            <td width="30%" style="padding-left:20px" >
                                <?php if(isset($userfetch["profile_picture"]) && $userfetch["profile_picture"]): ?>
                                    <img src="../uploads/profile_pictures/<?php echo htmlspecialchars($userfetch["profile_picture"]); ?>" alt="" width="100%" style="border-radius:50%">
                                <?php else: ?>
                                    <img src="../img/user.png" alt="" width="100%" style="border-radius:50%">
                                <?php endif; ?>
                            </td>
                            <td style="padding:0px;margin:0px;">
                                <p class="profile-title"><?php echo substr($pname,0,13)  ?>..</p>
                                <p class="profile-subtitle"><?php echo substr($useremail,0,22)  ?></p>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                            <a href="../logout.php" ><input type="button" value="Log out" class="logout-btn btn-primary-soft btn"></a>
                            </td>
                        </tr>
                </table>
                </td>
            
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-home" >
                    <a href="index.php" class="non-style-link-menu "><div><p class="menu-text">Home</p></div></a>
                </td>
            </tr>
            <tr class="menu-row">
                <td class="menu-btn menu-icon-doctor">
                    <a href="doctors.php" class="non-style-link-menu"><div><p class="menu-text">All Doctors</p></div></a>
                </td>
            </tr>
            
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-session">
                    <a href="schedule.php" class="non-style-link-menu"><div><p class="menu-text">Scheduled Sessions</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-appoinment">
                    <a href="appointment.php" class="non-style-link-menu"><div><p class="menu-text">My Bookings</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-feedback">
                    <a href="feedback.php" class="non-style-link-menu"><div><p class="menu-text">Feedback</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-report menu-active menu-icon-report-active">
                    <a href="reports.php" class="non-style-link-menu non-style-link-menu-active"><div><p class="menu-text">My Reports</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-payment">
                    <a href="payment_reports.php" class="non-style-link-menu"><div><p class="menu-text">My Payments</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-chatbot">
                    <a href="chatbot.php" class="non-style-link-menu"><div><p class="menu-text">Medical Assistant</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-settings">
                    <a href="settings.php" class="non-style-link-menu"><div><p class="menu-text">Settings</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-heart">
                    <a href="../health-tips-public.php" class="non-style-link-menu"><div><p class="menu-text">Health Tips</p></div></a>
                </td>
            </tr>
            <tr class="menu-row" >
                <td class="menu-btn menu-icon-notification">
                    <a href="notifications.php" class="non-style-link-menu notification-link"><div><p class="menu-text">Notifications</p><?php if($unreadNotificationsCount > 0): ?><span class="notification-dot"></span><?php endif; ?></div></a>
                </td>
            </tr>
        </table>
    </div>
    <?php 
    $selecttype="My Reports";
    $current = "My Reports";
    ?>

    <div class="dash-body">
        <table border="0" width="100%" style=" border-spacing: 0;margin:0;padding:0;margin-top:25px; ">
            <tr >
                <td width="13%" >
                <a href="index.php" ><button  class="login-btn btn-primary-soft btn btn-icon-back"  style="padding-top:11px;padding-bottom:11px;margin-left:20px;width:125px"><font class="tn-in-text">Back</font></button></a>
                </td>
                <td>
                    <p style="font-size: 23px;padding-left:12px;font-weight: 600;">My Reports</p>
                                       
                </td>
                <td width="15%">
                    <p style="font-size: 14px;color: rgb(119, 119, 119);padding: 0;margin: 0;text-align: right;">
                        Today's Date
                    </p>
                    <p class="heading-sub12" style="padding: 0;margin: 0;">
                        <?php 
                        date_default_timezone_set('Asia/Kolkata');
                        $date = date('Y-m-d');
                        echo $date;
                        ?>
                    </p>
                </td>
                <td width="10%">
                    <button  class="btn-label"  style="display: flex;justify-content: center;align-items: center;"><img src="../img/calendar.svg" width="100%"></button>
                </td>

            </tr>
            
            <tr>
                <td colspan="4" style="padding-top:10px;width: 100%;" >
                    
                    <p class="heading-main12" style="margin-left: 45px;font-size:18px;color:rgb(49, 49, 49)">Medical Documents</p>
                </td>
            </tr>
            
            <tr>
                <td colspan="4">
                    <center>
                        <div class="abc scroll">
                        <table width="93%" class="sub-table scrolldown" border="0">
                        <thead class="sticky-header">
                        <tr>
                                <th class="table-headin">
                                    Document Title
                                </th>
                                <th class="table-headin">
                                    Type
                                </th>
                                <th class="table-headin">
                                    Doctor
                                </th>
                                <th class="table-headin">
                                    Date
                                </th>
                                <th class="table-headin">
                                    Actions
                                </th>
                        </tr>
                        </thead>
                        <tbody>
                        
                            <?php
                            
                            // Check if document_image column exists
                            $check_column_sql = "SHOW COLUMNS FROM medical_documents LIKE 'document_image'";
                            $column_result = $database->query($check_column_sql);
                            $column_exists = $column_result->num_rows > 0;
                            
                            // Build query based on whether column exists
                            if ($column_exists) {
                                $sql_docs = "SELECT md.*, d.docname FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.patient_id = ? ORDER BY md.created_date DESC";
                            } else {
                                $sql_docs = "SELECT md.*, d.docname, NULL as document_image FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.patient_id = ? ORDER BY md.created_date DESC";
                            }
                            
                            $stmt_docs = $database->prepare($sql_docs);
                            $stmt_docs->bind_param("i", $pid);
                            $stmt_docs->execute();
                            $result_docs = $stmt_docs->get_result();

                            if($result_docs->num_rows==0){
                                echo '<tr>
                                <td colspan="5">
                                <br><br>
                                <center>
                                <p>No medical documents found.</p>
                                </center>
                                <br><br>
                                </td>
                                </tr>';
                            }
                            else{
                                while($doc = $result_docs->fetch_assoc()) {
                                    echo '<tr>
                                        <td>
                                        '.htmlspecialchars($doc["document_title"]).'
                                        </td>
                                        <td>
                                        '.ucfirst(str_replace('_', ' ', $doc["document_type"])).'
                                        </td>
                                        <td>
                                        Dr. '.htmlspecialchars($doc["docname"]).'
                                        </td>
                                        <td>
                                        '.date('M j, Y', strtotime($doc["created_date"])).'
                                        </td>
                                        <td>
                                        <div style="display:flex;justify-content: center;">
                                            <a href="?action=view_doc&id='.$doc["document_id"].'" class="non-style-link"><button class="btn-primary-soft btn button-icon btn-view">View</button></a>
                                            &nbsp;&nbsp;&nbsp;
                                            <a href="?action=print_doc&id='.$doc["document_id"].'" class="non-style-link"><button class="btn-primary-soft btn button-icon btn-print">Print</button></a>
                                        </div>
                                        </td>
                                    </tr>';
                                }
                            }
                            
                            ?>
 
                            </tbody>

                        </table>
                        </div>
                        </center>
                   </td> 
                </tr>
            </table>
        </div>
    </div>
    
    <?php
    
    if (isset($_GET['action']) && $_GET['action'] == 'view' && isset($_GET['id'])) {
        $appoid = $_GET['id'];

        $sql = "SELECT a.appoid, a.apponum, a.appodate, s.title, s.scheduledate, s.scheduletime, d.docname, d.docemail FROM appointment a JOIN schedule s ON a.scheduleid = s.scheduleid JOIN doctor d ON s.docid = d.docid WHERE a.appoid = ? AND a.pid = ?";
        $stmt = $database->prepare($sql);
        $stmt->bind_param("ii", $appoid, $pid);
        $stmt->execute();
        $result = $stmt->get_result();
        $appointment = $result->fetch_assoc();
        $stmt->close();
        
        echo '
        <div id="popup1" class="overlay">
            <div class="popup">
                <center>
                    <h2>Appointment Details</h2>
                    <a class="close" href="reports.php">&times;</a>
                    <div class="content">
                        <table width="80%" class="sub-table scrolldown add-doc-form-container" border="0">
                            <tr>
                                <td>
                                    <p style="padding: 0;margin: 0;text-align: left;font-size: 25px;font-weight: 500;">Appointment Details</p><br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="reference" class="form-label">Reference Number: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    OC-000-'.$appointment['appoid'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="doctor" class="form-label">Doctor: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    Dr. '.$appointment['docname'].' ('.$appointment['docemail'].')<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="session" class="form-label">Session: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['title'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="datetime" class="form-label">Date & Time: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['scheduledate'].' @ '.substr($appointment['scheduletime'],0,5).'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="bookingdate" class="form-label">Booking Date: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['appodate'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <a href="reports.php"><input type="button" value="OK" class="login-btn btn-primary-soft btn" ></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </center>
            </div>
        </div>';
    }

    if (isset($_GET['action']) && $_GET['action'] == 'print' && isset($_GET['id'])) {
        $appoid = $_GET['id'];

        $sql = "SELECT a.appoid, a.apponum, a.appodate, s.title, s.scheduledate, s.scheduletime, d.docname, d.docemail FROM appointment a JOIN schedule s ON a.scheduleid = s.scheduleid JOIN doctor d ON s.docid = d.docid WHERE a.appoid = ? AND a.pid = ?";
        $stmt = $database->prepare($sql);
        $stmt->bind_param("ii", $appoid, $pid);
        $stmt->execute();
        $result = $stmt->get_result();
        $appointment = $result->fetch_assoc();
        $stmt->close();
        
        echo '
        <div id="popup1" class="overlay">
            <div class="popup">
                <center>
                    <h2>Print Appointment</h2>
                    <a class="close" href="reports.php">&times;</a>
                    <div class="content">
                        <table width="80%" class="sub-table scrolldown add-doc-form-container" border="0">
                            <tr>
                                <td>
                                    <p style="padding: 0;margin: 0;text-align: left;font-size: 25px;font-weight: 500;">Appointment Confirmation</p><br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="reference" class="form-label">Reference Number: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    OC-000-'.$appointment['appoid'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="doctor" class="form-label">Doctor: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    Dr. '.$appointment['docname'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="session" class="form-label">Session: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['title'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="datetime" class="form-label">Date & Time: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['scheduledate'].' @ '.substr($appointment['scheduletime'],0,5).'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    <label for="bookingdate" class="form-label">Booking Date: </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label-td" colspan="2">
                                    '.$appointment['appodate'].'<br><br>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <button onclick="window.print()" class="login-btn btn-primary btn">Print</button>
                                    <a href="reports.php"><input type="button" value="Close" class="login-btn btn-primary-soft btn" ></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </center>
            </div>
        </div>';
    }
    
    // View medical document
    if (isset($view_doc_id)) {
        $doc_id = $view_doc_id;
        
        // Verify that the document belongs to this patient
        // Check if document_image column exists
        $check_column_sql = "SHOW COLUMNS FROM medical_documents LIKE 'document_image'";
        $column_result = $database->query($check_column_sql);
        $column_exists = $column_result->num_rows > 0;
        
        // Build query based on whether column exists
        if ($column_exists) {
            $sql = "SELECT md.*, d.docname FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.document_id = ? AND md.patient_id = ?";
        } else {
            $sql = "SELECT md.*, d.docname, NULL as document_image FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.document_id = ? AND md.patient_id = ?";
        }
        
        $stmt = $database->prepare($sql);
        $stmt->bind_param("ii", $doc_id, $pid);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            $document = $result->fetch_assoc();
            
            echo '
            <div id="popup1" class="overlay" style="visibility: visible; opacity: 1; background-color: rgba(0,0,0,0.7);">
                <div class="popup" style="max-width: 90vw; max-height: 90vh; width: auto; height: auto; overflow: auto; margin: 5vh auto;">
                    <center>
                        <h2 style="margin: 10px 0 15px 0;">'.htmlspecialchars($document['document_title']).'</h2>
                        <a class="close" href="reports.php" style="position: absolute; top: 15px; right: 20px; font-size: 30px; text-decoration: none; color: #333;">&times;</a>
                        <div class="content" style="padding: 20px;">
                            <table width="95%" class="sub-table scrolldown add-doc-form-container" border="0" style="margin: 0 auto;">
                                <tr>
                                    <td>
                                        <p style="padding: 0;margin: 0 0 10px 0;text-align: left;font-size: 20px;font-weight: 500;">'.ucfirst(str_replace('_', ' ', $document['document_type'])).'</p>
                                        <p style="padding: 0;margin: 0 0 20px 0;text-align: left;font-size: 16px;color: #666;">Generated by Dr. '.htmlspecialchars($document['docname']).' on '.date('F j, Y', strtotime($document['created_date'])).'</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label-td" colspan="2">
                                        <div class="document-content">'.nl2br(htmlspecialchars($document['document_content'])).'</div><br><br>
                                    </td>
                                </tr>';
                                // Add image if available and column exists
                                if ($column_exists && !empty($document['document_image'])) {
                                    // Construct the image path correctly from the patient directory
                                    // The document_image value is stored as 'uploads/document_images/filename.ext'
                                    // From the patient directory, we need to go up one level to reach the uploads folder
                                    $full_image_path = '../' . $document['document_image'];
                                    echo '<tr>
                                        <td class="label-td" colspan="2">
                                            <div style="text-align: center; margin: 20px 0;">
                                                <img src="'.$full_image_path.'" alt="Document Image" style="max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; max-height: 400px; object-fit: contain;">
                                            </div><br><br>
                                        </td>
                                    </tr>';
                                }
                                echo '<tr>
                                    <td colspan="2" style="text-align: center; padding: 20px 0;">
                                        <a href="reports.php"><input type="button" value="Close" class="login-btn btn-primary-soft btn" style="margin-right: 10px;" ></a>
                                        <a href="?action=print_doc&id='.$doc_id.'"><input type="button" value="Print" class="login-btn btn-primary btn" ></a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </center>
                </div>
            </div>';
        } else {
            // Document not found or doesn't belong to this patient
            header("location: reports.php");
        }
    }

    // Print medical document
    if (isset($_GET['action']) && $_GET['action'] == 'print_doc' && isset($_GET['id'])) {
        $doc_id = $_GET['id'];
        
        // Verify that the document belongs to this patient
        // Check if document_image column exists
        $check_column_sql = "SHOW COLUMNS FROM medical_documents LIKE 'document_image'";
        $column_result = $database->query($check_column_sql);
        $column_exists = $column_result->num_rows > 0;
        
        // Build query based on whether column exists
        if ($column_exists) {
            $sql = "SELECT md.*, d.docname FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.document_id = ? AND md.patient_id = ?";
        } else {
            $sql = "SELECT md.*, d.docname, NULL as document_image FROM medical_documents md JOIN doctor d ON md.doctor_id = d.docid WHERE md.document_id = ? AND md.patient_id = ?";
        }
        
        $stmt = $database->prepare($sql);
        $stmt->bind_param("ii", $doc_id, $pid);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            $document = $result->fetch_assoc();
            
            echo '
            <div id="popup1" class="overlay" style="visibility: visible; opacity: 1; background-color: rgba(0,0,0,0.7);">
                <div class="popup" style="max-width: 90vw; max-height: 90vh; width: auto; height: auto; overflow: auto; margin: 5vh auto;">
                    <center>
                        <h2 style="margin: 10px 0 15px 0;">Print '.htmlspecialchars($document['document_title']).'</h2>
                        <a class="close" href="reports.php" style="position: absolute; top: 15px; right: 20px; font-size: 30px; text-decoration: none; color: #333;">&times;</a>
                        <div class="content" style="padding: 20px;">
                            <table width="95%" class="sub-table scrolldown add-doc-form-container" border="0" style="margin: 0 auto;">
                                <tr>
                                    <td>
                                        <p style="padding: 0;margin: 0 0 10px 0;text-align: left;font-size: 20px;font-weight: 500;">'.ucfirst(str_replace('_', ' ', $document['document_type'])).'</p>
                                        <p style="padding: 0;margin: 0 0 20px 0;text-align: left;font-size: 16px;color: #666;">Generated by Dr. '.htmlspecialchars($document['docname']).' on '.date('F j, Y', strtotime($document['created_date'])).'</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label-td" colspan="2">
                                        <div class="document-content">'.nl2br(htmlspecialchars($document['document_content'])).'</div><br><br>
                                    </td>
                                </tr>';
                                // Add image if available and column exists
                                if ($column_exists && !empty($document['document_image'])) {
                                    // Construct the image path correctly from the patient directory
                                    // The document_image value is stored as 'uploads/document_images/filename.ext'
                                    // From the patient directory, we need to go up one level to reach the uploads folder
                                    $full_image_path = '../' . $document['document_image'];
                                    echo '<tr>
                                        <td class="label-td" colspan="2">
                                            <div style="text-align: center; margin: 20px 0;">
                                                <img src="'.$full_image_path.'" alt="Document Image" style="max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; max-height: 400px; object-fit: contain;">
                                            </div><br><br>
                                        </td>
                                    </tr>';
                                }
                                echo '<tr>
                                    <td colspan="2" style="text-align: center; padding: 20px 0;">
                                        <button onclick="window.print()" class="login-btn btn-primary btn" style="margin-right: 10px;">Print</button>
                                        <a href="reports.php"><input type="button" value="Close" class="login-btn btn-primary-soft btn" ></a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </center>
                </div>
            </div>';
        } else {
            // Document not found or doesn't belong to this patient
            header("location: reports.php");
        }
    }
    ?>
</body>
</html>